config/routes.rb
Rails.application.routes.draw do
  
  
  root 'pages#home'
  resources :worklogs
  get 'about', to: 'pages#about'
  #get 'signup', to: 'users#new'
  resources :users, except: [:new]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, 
               uniqueness: {case_sensitive: false}, 
               length: {minimum: 3, maximum: 20}

    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

    validates :email, presence: true, 
               uniqueness: {case_sensitive: false}, 
               length: {minimum: 3, maximum: 50},
               format: {with: VALID_EMAIL_REGEX}
    
    has_secure_password 


end

app/models/worklog.rb
class Worklog < ApplicationRecord
    belongs_to :user
    validates :Beschreibung, presence: true, length: { minimum: 3, maximum: 100 }
    validates :Anzahl_Arbeiter, presence: true, length: { minimum: 1, maximum: 4 }
    validates :Stunden, presence: true, length: { minimum: 1, maximum: 300 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
  
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    def logged_in?
      !!current_user
    end
  
    def require_user
      if !logged_in?
        flash[:alert] = "You must be logged in to perform that action"
        redirect_to login_path
      end
    end
  
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to worklogs_path if logged_in?
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = "Logged in successfully"
        redirect_to user
      else
        flash.now[:alert] = "There was something wrong with your login details"
        render 'new'
      end
    end
  
    def destroy
      session[:user_id] = nil
      flash[:notice] = "Logged out"
      redirect_to root_path
    end
  
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]
  
    def show
      redirect_to worklogs_path
      #@worklogs = @user.worklog.paginate(page: params[:page], per_page: 5)
    end
  
    def index
      @user = User.all #paginate(page: params[:page], per_page: 5)
    end
  
    def new
      @user = User.new
    end
  
    def edit
    end
  
    def update
      if @user.update(user_params)
        flash[:notice] = "Your account information was successfully updated"
        redirect_to @user
      else
        render 'edit'
      end
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Welcome to UKW2's Worklog Tool #{@user.username}, you have successfully signed up"
        redirect_to worklogs_path
      else
        render 'new'
      end
    end
  
    def destroy
      @user.destroy
      session[:user_id] = nil if @user == current_user
      flash[:notice] = "Account and all associated worklogs
       successfully deleted"
      redirect_to worklogs
      _path
    end
  
    private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
  
    def set_user
      @user = User.find(params[:id])
    end
  
    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own account"
        redirect_to @user
      end
    end
end
    

app/controllers/worklogs_controller.rb
class WorklogsController < ApplicationController
  #before_action :set_worklog, only: %i[ show edit update destroy ]
  before_action :set_worklog, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /worklogs or /worklogs.json
  def index
    @worklogs = Worklog.all #paginate(page: params[:page], per_page: 5)
  end

  # GET /worklogs/1 or /worklogs/1.json
  def show
  end

  # GET /worklogs/new
  def new
    @worklog = Worklog.new
  end

  # GET /worklogs/1/edit
  def edit
  end

  # POST /worklogs or /worklogs.json
  def create
    @worklog = Worklog.new(worklog_params)
    @worklog.user = current_user

    respond_to do |format|
      if @worklog.save 
        format.html { redirect_to @worklog, notice: "Worklog was successfully created." }
        format.json { render :show, status: :created, location: @worklog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @worklog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worklogs/1 or /worklogs/1.json
  def update
    respond_to do |format|
      if @worklog.update(worklog_params)
        format.html { redirect_to @worklog, notice: "Worklog was successfully updated." }
        format.json { render :show, status: :ok, location: @worklog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worklog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worklogs/1 or /worklogs/1.json
  def destroy
    @worklog.destroy
    respond_to do |format|
      format.html { redirect_to worklogs_url, notice: "Worklog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def require_same_user
    if current_user != @worklog.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own worklog"
      redirect_to @worklog
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worklog
      @worklog = Worklog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worklog_params
      params.require(:worklog).permit(:Beschreibung, :Anzahl_Arbeiter, :Arbeiter_01, :Arbeiter_02, :Arbeiter_03, :Arbeiter_04, :Stunden, :Datum, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
      email_address = user.email.downcase
      hash = Digest::MD5.hexdigest(email_address)
      size = options[:size]
      gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
      image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end
  
  end

app/helpers/worklogs_helper.rb
module WorklogsHelper
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Thomas Lang", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "UKW2 Worklog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Worklog
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <% if logged_in? %>
              <%= link_to "Worklog", worklogs_path, class: "dropdown-item" %>
             
           <% end %> 
              
  
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %> 
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <!-- <li class="nav-item">
          <%#= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li> -->
      <% end %>
      </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UKW2 Worklog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head) %> 
  </head>

   <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>
<%= link_to 'Worklogs listing', worklogs_path %> |
<%= link_to 'Home page', root_path %>

<% content_for :head do %>
    <%= stylesheet_link_tag 'https://cdn.dhtmlx.com/gantt/edge/dhtmlxgantt.css' %>
    <%= javascript_include_tag 'https://cdn.dhtmlx.com/gantt/edge/dhtmlxgantt.js' %>
<% end %>
 
<div id="gantt_here" style='width:100%; height:800px;'></div>
 
<script>
    gantt.init("gantt_here");
</script>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-black">
    <h1 class="display-4">UKW2 Worklog</h1>
    <hr class="my-4">
    <a class="btn btn-success btn-lg" role="button">Login </a>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="from-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter username" %>
          </div>
        </div>

        <div class="from-group row " >
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
           <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter email address" %>
          </div>
        </div>

        <div class="from-group row " >
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
           <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter password " %>
          </div>
        </div>

        <div class="form-group row justify-content-center" >
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
     <div class="mb-3">
      <%= link_to '[ Cancel and return to worklogs listing ]', worklogs_path, class: "text-info" %>
    </div>
  
  </div>
</div>
  
  

  

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">UKW2 Worklog</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.worklog.count, "worklog") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: :delete,
                data: {confirm: "Are you sure you want to delete the user account and all associated worklog?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @worklog, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Log in</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>
<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Worklog</h3>

<div class="flickr_pagination">
  <%= will_paginate @worklog, :container => false %>
</div>

<%= render 'worklogs/worklog' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @worklog, :container => false %>
</div>

app/views/worklogs/_form.html.erb
<style>
div{
  
}
.field {
 
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

#label_{
  width: 5000px;
  
}
.actions {
  margin-top: 20px;
}

</style>
<%= form_with(model: worklog) do |form| %>
  <% if worklog .errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worklog.errors.count, "error") %> prohibited this worklog from being saved:</h2>

      <ul>
        <% worklog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Beschreibung, class:"label_" %> 
    <%= form.text_area :Beschreibung, :rows=>10, :cols=>60%>
  </div>

  <div class="field">
    <%= form.label :Anzahl_Arbeiter %>
    <%= form.number_field :Anzahl_Arbeiter %>
  </div>

  <div class="field">
    <%= form.label :Arbeiter_01 %>
    <%= form.text_field :Arbeiter_01 %>
  </div>

  <div class="field">
    <%= form.label :Arbeiter_02 %>
    <%= form.text_field :Arbeiter_02 %>
  </div>

  <div class="field">
    <%= form.label :Arbeiter_03 %>
    <%= form.text_field :Arbeiter_03 %>
  </div>

  <div class="field">
    <%= form.label :Arbeiter_04 %>
    <%= form.text_field :Arbeiter_04 %>
  </div>

  <div class="field">
    <%= form.label :Stunden %>
    <%= form.number_field :Stunden %>
  </div>

  <div class="field">
    <%= form.label :Datum %>
    <%= form.date_select :Datum %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/worklogs/edit.html.erb
<h1>Editing Worklog</h1>

<%= render 'form', worklog: @worklog %>

<%= link_to 'Show', @worklog %> |
<%= link_to 'Back', worklogs_path %>

app/views/worklogs/index.html.erb
<h1>Worklogs</h1>

<table class="table table-striped table-dark"
  <thead>
    <tr>
      <th scope="col">Beschreibung</th>
      <th scope="col">Anzahl arbeiter</th>
      <th scope="col">Arbeiter 01</th>
      <th scope="col">Arbeiter 02</th>
      <th scope="col">Arbeiter 03</th>
      <th scope="col">Arbeiter 04</th>
      <th scope="col">Stunden</th>
      <th scope="col">Datum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @worklogs.each do |worklog| %>
      <tr>
        <td><%= worklog.Beschreibung %></td>
        <td><%= worklog.Anzahl_Arbeiter %></td>
        <td><%= worklog.Arbeiter_01 %></td>
        <td><%= worklog.Arbeiter_02 %></td>
        <td><%= worklog.Arbeiter_03 %></td>
        <td><%= worklog.Arbeiter_04 %></td>
        <td><%= worklog.Stunden %></td>
        <td><%= worklog.Datum %></td>
        <td><%= link_to 'Show', worklog %></td>
        <td><%= link_to 'Edit', edit_worklog_path(worklog) %></td>
        <td><%= link_to 'Destroy', worklog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Worklog', new_worklog_path, :method => "get" %>

app/views/worklogs/new.html.erb
<h1>New Worklog</h1>


<%= render 'form', worklog: @worklog %>

<%= link_to 'Back', worklogs_path %>

app/views/worklogs/show.html.erb
<table class="table table-striped table-dark">
  <tr>
    <td><strong><%= @worklog.Beschreibung %></strong></td>
    <td><strong><%= @worklog.Anzahl_Arbeiter %></strong></td>
    <td><strong>  <%= @worklog.Arbeiter_01 %></strong></td>
    <td><strong><%= @worklog.Arbeiter_02 %></strong></td>
    <td><strong><%= @worklog.Arbeiter_03 %></strong></td>
    <td><strong><%= @worklog.Arbeiter_04 %></strong></td>
    <td><strong><%= @worklog.Stunden %></strong></td>
    <td><strong> <%= @worklog.Datum %></strong></td>
  </tr>
  </table>

<%= link_to 'Edit', edit_worklog_path(@worklog) %> 
<%= link_to 'Back', worklogs_path %>